### ISSUE TITLE
Use verb in the title

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/creating-build-scans#1]
@kousen Titles of all other getting started guides already available at https://gradle.org/docs start with a verb. Wouldn't it better to rename this one to "Creating Basic Build Scans" for consistency?

**Comment by alkemist** [comment]
My vote is for “Creating a build scan”

**Comment by pioterj** [comment]
I like "Creating build scans". Using plural would be consistent with the other guides. All of those titles are implicitly "getting started" so "Getting started creating build scans" makes sense even if you create a single build scan as a part of this guide.

**Comment by pioterj** [comment]
@kousen I don't see it fully changed yet:
- URL is still https://guides.gradle.org/basic-build-scans/
- The link name is still "Basic Build Scans" on https://gradle.org/docs#guides

**Comment by ysb33r** [comment]
Let me take care of the renaming as I'll be doing another repo renaem wth @chaficnajjar on Thursday.

- [ ] Change repo name to `creating-build-scans`
- [ ] Update `dotog-site` with index change & CloudFlare redirect.

**Comment by ysb33r** [comment]
Done.
