### ISSUE TITLE
Scan terms of service

### ISSUE THREAD

**Issue by Peter-Farlow-Intrepid** [gradle-guides/creating-build-scans#16]
I'm trying to carefully read the Gradle terms of service. What exactly gets uploaded to gradle's non-enterprise build scan service when I add `--scan` to my command line options? Does any code from my project get uploaded? Does the scan only upload build meta data, like task names, their lengths, and their dependencies?

**Comment by eriwen** [comment]
Hi @Peter-Farlow-Intrepid 

Please see [this document on captured information](https://docs.gradle.com/build-scan-plugin/#captured_information). 

Here's a snippet:

> Notably, the actual source code being built and the output artifacts are not captured. However, error messages emitted by compilers or errors in tests may reveal aspects of the source code.

Please comment on this issue if this doesn't fully answer your question.
