### ISSUE TITLE
Figure shows tag "Gradleware"

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/creating-build-scans#6]
The company "Gradleware" does not exist anymore. The figure should be correct to not say that.

https://guides.gradle.org/creating-build-scans/#access_the_scan_online

**Comment by etiennestuder** [comment]
@facewindu Can you please take care of this?

**Comment by facewindu** [comment]
handled in https://github.com/gradle-guides/creating-build-scans/pull/9
